### ISSUE TITLE
Update Readme: Unity Plugin references missing link to releases.  

### ISSUE THREAD

**Issue by dzeitman** [DolbyIO/comms-sdk-dotnet#113]
Please update the first paragraph to include the following information (link to releases was missing)

The Unity plugin is built on top of the .NET SDK with visual scripting support. 
You can find latest releases of the Unity Plugin here:
https://github.com/DolbyIO/comms-sdk-dotnet/releases
Refer to this [article](https://api-references.dolby.io/comms-sdk-dotnet/documentation/unity/unity.html) for installing and using the Unity plugin.

**Comment by jfan-dolby** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/18742413/210273336-0f8316d8-5afd-415e-be71-24ef611a36ac.png">
The link to this page is not clear?

**Comment by jfan-dolby** [comment]
This has been addressed in https://github.com/DolbyIO/comms-sdk-dotnet/pull/115, closing issue.
