### ISSUE TITLE
Readme:  Mixed description and Purpose of this SDK is confusing - requires more context in the readme.

### ISSUE THREAD

**Issue by dzeitman** [DolbyIO/comms-sdk-dotnet#114]
Unity developers will be confused with the way the readme lays out the purpose of this repo.
The generally expect a stand-alone repo for the Unity Plugin package

What we present here is a mixed repo of both .Net and Unity -- its confusing and the descriptive text to get started is out of context.

Suggestions for improving the clarity.  
See Issue: https://github.com/DolbyIO/comms-sdk-dotnet/issues/113

### Get Started with the Unity Plugin

The Unity plugin is built on top of the .NET SDK with visual scripting support.
You can find latest releases of the Unity Plugin here:
https://github.com/DolbyIO/comms-sdk-dotnet/releases
Refer to this [article](https://api-references.dolby.io/comms-sdk-dotnet/documentation/unity/unity.html) for installing and using the Unity plugin.

[Insert text:] 
### Getting Started with the .Net SDK

The following guide presents an example of using the SDK to create a basic .NET audio-only conference application. 
In this repo we will proved a starter project example for using the .NET SDK.
You can create by following this procedure provides the foundation upon which you can add additional features as you build out your application.

You can find the complete code for the application in the [Summary](https://github.com/DolbyIO/comms-sdk-dotnet/issues/new#summary) section. The created application is available in the [SimpleApp](https://github.com/DolbyIO/comms-sdk-dotnet/tree/master/samples/SimpleApp) folder.

**Comment by jfan-dolby** [comment]
feel free to create a PR with these suggestions.
