### ISSUE TITLE
Update to C++ SDK 2.5 in .NET SDK

### ISSUE THREAD

**Issue by GaryMakinDolby** [DolbyIO/comms-sdk-dotnet#159]
Support the latest 2.5 release, which is currently 2.5.1.

See https://github.com/DolbyIO/comms-sdk-cpp

**Comment by djova-dolby** [comment]
Small correction, should be updated to [C++SDK 2.5.3](https://github.com/DolbyIO/comms-sdk-cpp/releases/tag/2.5.3)
